### PR TITLE
Add support for managing workspace access

### PR DESCRIPTION
**Pull request by ladlavj**
new resource resource_workspace_access to manage workspace access to apps, security groups, and users.

### CODE REVIEW

**Comment by ladlavj** [comment]
@alex-davies, please have a look at this PR as GitHub action tests were not initiated due to branch to branch PR.

**Comment by alex-davies** [comment]
Thanks again for implementing this

I have pulled your changes into a separate branch ( https://github.com/codecutout/terraform-provider-powerbi/pull/17) so I could perform the rebase and do some minor tweaks to get the tests running on the build server

Unfortunately github doesn't seem to associate your commits to your github username so my PR doesn't give you credit for your contributions. If you want to recognition for your changes i'm happy for you to reraise my PR in your name

**Comment by ladlavj** [comment]
Thats great if you can do so, or let me know if I have to raise PR again to master, as you have already merged branch client-credential to master.

**Comment by alex-davies** [comment]
Yes i've merged the client-credential change and i've rebased your workspace-access changes on the new master and done a few minor changes to update docs and get the automated build running. I have it on a branch on a `feature/workspace-access` branch in this repo. 

If you create the PR from that branch to master (https://github.com/codecutout/terraform-provider-powerbi/compare/master...feature/workspace-access) I will merge and it should mean you get your github name on the squash merge commit.

If you not concerned about having your name on the commit let me know and I can go ahead and raise it myself. But you do deserve credit for the commit

**Comment by ladlavj** [comment]
> Yes i've merged the client-credential change and i've rebased your workspace-access changes on the new master and done a few minor changes to update docs and get the automated build running. I have it on a branch on a `feature/workspace-access` branch in this repo.
> 
> If you create the PR from that branch to master ([master...feature/workspace-access](https://github.com/codecutout/terraform-provider-powerbi/compare/master...feature/workspace-access)) I will merge and it should mean you get your github name on the squash merge commit.
> 
> If you not concerned about having your name on the commit let me know and I can go ahead and raise it myself. But you do deserve credit for the commit

Thanks, I've raised new PR #18 from this branch

**Pull request closed without merging**
